# Generated by Django 5.1.4 on 2024-12-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tickets",
            "0002_tickettype_alter_ticket_options_remove_ticket_title_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="is_valid",
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[("valid", "Valid"), ("used", "Used")],
                default="valid",
                max_length=10,
            ),
        ),
    ]
